parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sk
    database_user: estate
    database_password: real
    
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    
    locale: en
    secret: 87b3c17fb327518c05b1c450462c81904913407e
    
    database_path: null
